# Custom Language File for Launcher Customizer

[ejs.app]
title = "CYML"

[ejs.landing]
mediaHomeURL = "#"
mediaLinkURL = "#"
mediaMapURL = "#"
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "CYML"
welcomeDescription = ""
welcomeDescCTA = ""
